### ISSUE TITLE
/glist breaks sporadically

### ISSUE THREAD

**Issue by mdcfe** [N3FS/issues#14]
Under some circumstances `/glist` stops working. Possible Velocity bug, since the command is implemented as part of Velocity itself - investigate this.

**Comment by jackmawer** [comment]
This might be related to velocity 1.0.5. Since updating to 1.0.6 this issue appears to have gone away, but it's worth continuing to monitor just in case.

**Comment by mdcfe** [comment]
It turns out Neutron's glist implementation wasn't fully disabled, causing the command to get partially registered and override Velocity's built-in glist when `/velocity reload` is run. I fixed this a while ago by removing the config section entirely, which prevents the command getting registered and we're now using Velocity's glist.
